### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by Xikaro** [X-Niter/AE2WirelessTerminalLibrary#1]
**Describe the bug**
New version 1.0.8.0 is not recognized as a dependency

**Screenshots**
![Screenshot_227](https://user-images.githubusercontent.com/55663835/184508383-eabf217f-f8c6-47bb-88e6-74780af03bd1.png)

**Comment by X-Niter** [comment]
@Xikaro , I can apply a dirty patch to this in about 5 minutes, of course waiting for Curseforge after that. 

But, given that I completely forgot about these other terminal mods requiring this mod, I actually might look into just combining the other terminals into this mod, that way it's less overhead on initialization and loading and common classes/function can be used resulting in less processesing to go down.

**Comment by Xikaro** [comment]
come on, that'll be cool))

**Comment by X-Niter** [comment]
Go ahead and give this a go! Let me know how it goes, mate!

Unzip it and the jar is there. 

If it's good then I'll go ahead and push this patch and then look into making a big change by bringing the other terminal in for a future update. 
[AE2WTLib-1.12.2-1.0.35.zip](https://github.com/X-Niter/AE2WirelessTerminalLibrary/files/9332087/AE2WTLib-1.12.2-1.0.35.zip)

**Comment by Xikaro** [comment]
there are some bugs in these mods that I would like to solve, for example, the display of patterns in the terminal, since in the interface
AE2 Unofficial Extended Life is now an expanded number of them, and only the first line is displayed

**Comment by X-Niter** [comment]
Wireless terminals are only showing one line when you use them with AE2 Unofficial Extended Life?? 

Do I understand that correctly?

**Comment by Xikaro** [comment]
yep

**Comment by Xikaro** [comment]
AE2WTLib-1.12.2-1.0.35.jar everything is working
