### ISSUE TITLE
New curse version

### ISSUE THREAD

**Issue by Xikaro** [X-Niter/AE2WirelessTerminalLibrary#2]
Will the version listed in #1 be published? this is important as our build is published there and will use your mod

**Comment by X-Niter** [comment]
Hey @Xikaro , sorry it seems are time zone is almost opposite of each other.
As of sending this message, It has been uploaded to Curse Forge and awaiting there ususal approval.

**Comment by Xikaro** [comment]
Thanks, I'm looking forward to combining other AE2 Wireless Terminal mods))
